language: php

php:
  - 7.1
  - 7.2

install:
  - cp .env.example .env
  - composer self-update
  - composer update --no-interaction

  # Install coveralls.phar
  - wget -c -nc --retry-connrefused --tries=0 https://github.com/php-coveralls/php-coveralls/releases/download/v2.0.0/php-coveralls.phar -O coveralls.phar
  - chmod +x coveralls.phar
  - php coveralls.phar --version

# Create a storage folder for coverage report
before_script:
  - mkdir -p build/logs
  - ls -al

script:
  - ./vendor/bin/phpunit --coverage-clover build/logs/clover.xml

#after_script:
#  - bin/coveralls -v
after_success:
  # Submit coverage report to Coveralls servers, see .coveralls.yml
  - travis_retry php coveralls.phar -v

# Tell Travis CI to monitor only 'master' branch
branches:
  only: main

# You can delete the cache using travis-ci web interface
cache:
  directories:
    - vendor
    - $HOME/.cache/composer
